# Database Connectivity
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d9lq9dmgekts73ccp600-a.oregon-postgres.render.com:5432/donadores_entidades_db_bl0b}
spring.datasource.username=${DB_USERNAME:jajava}
spring.datasource.password=${DB_PASSWORD:KqbtlHExgMNrTjgUxvhQhHCgfRON4nkV}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}
spring.jpa.properties.hibernate.dialect=${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

# API Configuration
incentivos.api.base-url=${INCENTIVOS_API_BASE_URL:https://incentivos-yuse.onrender.com}
donaciones.api.base-url=${DONACIONES_API_BASE_URL:https://donaciones-5u8i.onrender.com}
logistica.api.base-url=${LOGISTICA_API_BASE_URL:https://logistica-hjaw.onrender.com}

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# DevTools Configuration
spring.devtools.restart.enabled=true

# Server Configuration for Dockerfile
server.port=${PORT:8080}

# Micrometer configuration for monitoring
management.datadog.metrics.export.api-key=${DATADOG_API_KEY}
management.datadog.metrics.export.enabled=${DATADOG_METRICS_ENABLED:false}
management.datadog.metrics.export.uri=${DATADOG_METRICS_URI}
management.datadog.metrics.export.step=30s
